baseURL = "https://mosm.dev"
languageCode = "en-us"
title = "mosm.dev"
theme = "cactus"
# copyright = "" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set

# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Projects"
url = "/projects"
weight = 2

[[menu.main]]
name = "Misc"
url = "/misc"
weight = 3

# [[menu.main]]
# name = "Writings"
# url = "/posts"
# weight = 4

# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 5

[markup]
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = false
noClasses = true
style = "monokai"
tabWidth = 4

[params]
colortheme = "white"        # dark, light, white, or classic
rss = false                 # generate rss feed. default value is false
showAllPostsArchive = false # default

# Home page settings
description = ""
mainSection = "posts"                       # your main section
showAllPostsOnHomePage = false              # default
postsOnHomePage = 5                         # this option will be ignored if showAllPostsOnHomePage is set to true
tagsOverview = true                         # show tags overview by default.
showProjectsList = true                     # show projects list by default (if projects data file exists).
projectsUrl = "https://github.com/gohugoio" # title link for projects list

# https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
dateFormat = "2006-01-02" # default

# Post page settings
show_updated = true  # default
showReadTime = false # default

#[params.comments]
#enabled = false            # default
#engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
#[params.comments.utterances]
#repo = "<github_username>/<github_reponame>"
#label = "hugo-site-name"                     # you can use however you want to label your name in your repo's issues
#theme = "github-light"
#[params.comments.cactuscomments]
#siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
#serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
#serverName = "" # Defaults to cactus.chat

# the value of name should be an valid font awesome icon name (brands type)
# https://fontawesome.com/icons?d=gallery&s=brands
[[params.social]]
name = "github"
link = "https://github.com/mosmeh"
[[params.social]]
name = "twitter"
link = "https://twitter.com/mosmeh"
[[params.social]]
name = "email"
link = "yuta.imazu@gmail.com" # no need for "mailto:" in the head
