name: build

on:
    workflow_dispatch:
    push:
        branches: [master]

jobs:
    deploy:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: peaceiris/actions-hugo@v2
            - run: hugo -e production --minify
            - uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  enable_jekyll: false
                  commit_message: ${{ github.event.head_commit.message }}
                  force_orphan: true
